-- Interests stop being admin-curated only. Anyone can add one, and two people who type the
-- same tag get the same row -- which is what makes "you both like xyz" a fact rather than a
-- coincidence: matching still runs on one shared vocabulary (aim.md 4.3), that vocabulary can
-- now grow from the people using it.
--
-- `id` was a manually assigned smallint with 28 rows seeded by hand. A row created from the
-- setup screen has no such number to give it, so the column needs to generate its own.
alter table interests alter column id add generated by default as identity;
select setval(pg_get_serial_sequence('interests', 'id'), (select max(id) from interests));
